%%{init: {'themeVariables': { 'fontSize': '15px'}}}%%
%% Mermaid Mindmap: System Overview
mindmap
  root((Nodges))
    Core
      StateManager
      UIManager
      LayoutManager
      InteractionManager
      CentralEventManager
    Utils
      ImportManager
      ExportManager
      FutureDataParser
      FutureDataManager
      DataModelValidator
      RaycastManager
      SearchManager
      SelectionManager
      LayoutGUI
      NetworkAnalyzer
      PathFinder
      PerformanceOptimizer
      BatchOperations
      EdgeLabelManager
      NodeGroupManager
      NeighborhoodHighlighter
      GroundManager
      KeyboardShortcuts
      ConnectInterfaceAdapter
    Effects
      GlowEffect
      HighlightManager
    Objects
      Node
      Edge
      NodeMeshFactory
    Worker
      layout-worker
